# 45장 프로미스

- JS는 비동기 처리를 위한 방법 중 하나로 콜백 함수를 사용한다.
- 하지만 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고
- 비동기 처리 중 발생한 에러의 수정도 어렵기에 여러개의 비동기를 처리하기에 어려움이 많다.
- ES6에서는 이를 개선하기 위해 Promise 패턴을 도입했다.
- Promise로 콜백 패턴의 단점을 보완하며 비동기 처리 시점을 명확하게 표현 할 수 있다.

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 먼저 콜백의 의미를 다시 정리하자.

- 비동기 함수란 함수 내부에 비동기로 동작하는 코드를 포함한 함수를 말한다.
- **비동기 함수는 실행되면 내부의 비동기로 동작하는 코드가 완료되지 않아도 기다리지 않고 종료된다.**
- 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.
- **즉, 비동기 함수 내부의 비동기로 동작하는 코드는 처리 결과를 외부로 반환하거나 상위 스코프로 할당이 되지 않는다.**

> 때문에 비동기 함수의 처리 결과(내부의 비동기로 동작하는 코드)에 대한 후속 처리는  
> 비동기 함수 내부에서 수행되어야 한다. (후속 처리가 없으면 비동기 함수는 완료되어버린다.)

> 즉, 비동기 함수는 내부에서 비동기로 동작하는 코드의 결과를 처리해야 한다.  
> 그래서 <span style ="color : red">**내부의 비동기 동작으로 동작하는 함수를 비동기 함수에게 콜백 한다.** </span>

### 45.1.1 콜백 헬(Callback hell)

```
콜백 함수를 통해 비동기 함수 내부의 비동기 동작으로 움직이는 코드의 처리 결과를 한번만 처리한다면 문제가 없지만,
이 결과를 가지고 또 다시 비동기 함수를 호출해야 한다면 그 비동기 함수 내부의 콜백함수가 다시 호출되어 중첩이 발생하며
이는 코드를 복잡하게 만든다. 이를 콜백 헬이라 한다.
```

```js
// 유저정보를 가지고 있는 유저창고 클래스가 있다고 하자.
class UserStroage {
  // 유저창고는 로그인 메서드를 가지며
  loginUser(id, password, onSuccess, onError) {
    // 로그인 메서드는 setTimeout 비동기 함수로 성공여부를 콜백한다.
    setTimeout(() => {
      if (
        (id === "kim" && password === "123") ||
        (id === "lee" && password === "456")
      ) {
        onSuccess(id);
      } else {
        onError(new Error("not found"));
      }
    }, 2000);
  }

  // 유저창고는 사용자 정보를 확인하는 메서드를 가지며
  getRoles(user, onSuccess, onError) {
    // 정보 확인 메서드는 비동기 함수로 사용자 정보를 콜백한다.
    setTimeout(() => {
      if (user === "kim") {
        onSuccess({ name: "kim", role: "admin" });
      } else {
        onError(new Error("no access"));
      }
    }, 1000);
  }
}

const userStroage = new UserStroage();

const id = prompt("enter your id");
const password = prompt("enter your password");

// <콜백 헬>
// 로그인을 시도하면 로그인 메서드 내부의 콜백으로 성공 여부를 반환하고,
userStroage.loginUser(
  id,
  password,
  (user) => {
    // 성공 시 유저 이름을 가지고 콜백을 함수를 가진 다른 메서드 또 실행되고,
    userStroage.getRoles(
      user,
      // 반복된 콜백들의 반환 값으로 화면에 호출된다.
      (userWithRole) => {
        alert(`hi ${userWithRole.name}, ${userWithRole.role}`);
      },
      (error) => {
        console.log(error);
      }
    );
  },
  (error) => {
    console.log(error);
  }
);
```

> **콜백 헬은 가독성이 매우 좋지 않으며, 에러 처리에 어려움을 준다.**

### 45.1.2 에러 치리의 한계

```js
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  // 에러를 캐치하지 못한다
  console.error("캐치한 에러", e);
}
```

- 비동기 함수 setTimeout이 실행되고 종료된다.
- setTimeout는 비동기 함수미르모 콜백 함수 **호출을 기다리지 않는다**.
- 타이머가 완료되면 setTimeout의 콜백 함수가 콜 스택으로 푸쉬되어 실행된다.
- 콜백 함수가 실행될때 setTimeout는 이미 사라졌다.
- 즉, 콜백 함수를 호출한 것은 setTimeout가 아니다.
- 에러는 호출자 방향으로 전파된다.
- setTimeout는 호출자가 아니기에 에러를 캐치하지 못한다.

## 45.2 [Promise](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise) 생성

- 콜백함수로의 비동기를 보완하고자 도입된 Promise는 생성자 함수로 사용된다.
- Promise 생성자 함수는 **비동기 처리를 수행할 콜백 함수인 `resolve`와 `reject`를 전달 받는다**.

```js
const promise = new Promise((resolve, reject) => {
    if (/* 비동기 처리 성공 */) {
        resolve('결과')
    } else { /* 비동기 처리 실패 */
        reject('실패 이유')
    }
})
```

- 비동기 처리가 성공하면 resolve 함수를 호출하고 실패하면 reject 함수를 호출한다.

앞서 학습 했던 콜백함수의 의미를 다시 보자.

> 비동기 함수는 내부에서 비동기로 동작하는 코드의 결과를 처리해야 한다.  
> 그래서 내부의 비동기 동작으로 동작하는 함수를 비동기 함수에게 콜백 한다.  
> <span style ="color : red">**비동기 함수는 콜백 받은 결과를 함수 내부에서 처리해야한다.**</span>

```js
// 기존 GET 요청을 위한 비동기 함수 (콜백 헬)
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      successCallback(JSON.parse(xhr.response));
    } else {
      failureCallback(xhr.status);
    }
  };
};

get("https://jsonplaceholder.typicode.com/posts/1", console.log, console.error);

// Promise 생성자 함수를 반환하는 GET 요청 비동기 함수
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response));
      } else {
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet("https://jsonplaceholder.typicode.com/posts/1");
```

- 프로미스는 다음과 같이 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 갖는다.

| 프로미스의 상태 정보 | 의미                                  | 상태 변경 조건                   |
| -------------------- | ------------------------------------- | -------------------------------- |
| pending              | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled            | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected             | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

- 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경한다.
- 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경한다.
- 이처럼 프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정된다.

<img src="https://velog.velcdn.com/images/sarang_daddy/post/0ee57796-2074-43d7-805b-7f43c817e866/image.png" width="70%">

> fulfilled 또는 rejected 상태를 settled 상태라고 한다.  
> 이것은 pending이 아닌 비동기 처리가 수행된 상태를 말한다.

## 45.3 프로미스의 후속 처리 메서드

- 프로미스의 비동기 처리 상태가 변화하면 이에 따른 후속 처리를 해야 한다.
- 이를 위해 프로미스는 후속 메서드 then, catch, finally를 제공한다.

### 45.3.1 then

- then 메서드는 두 개으 콜백 함수를 전달 받는다.

1. 첫 번재 콜백 함수 : 프로미스가 fulfilled 상태가 되면 호출. 이때 콜백 함수는 비동기 처리 결과를 인수로 전달받는다.
2. 두 번째 콜백 함수: 프로미스가 rejected 상태가 되면 호출. 이때 콜백 함수는 에러를 인수로 전달받는다.

```js
// fulfilled
new Promise((resolve) => resolve("fulfilled")).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // fulfilled

// rejected
new Promise((_, reject) => reject(new Error("rejected"))).then(
  (v) => console.log(v),
  (e) => console.error(e)
); // Error: rejected
```

> **then 메서드는 언제나 프로미스를 반환한다.**

- 만약 then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 반환하고
- 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환한다.

### 45.3.2 catch

- catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- 이 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.
- then 메서드와 마찬가지로 프로미스를 반환한다.

### 45.3.3 finally

- finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- 이 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다.
- 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다.
- 마찬가지로 프로미스를 반환한다.

<img src="https://velog.velcdn.com/images/sarang_daddy/post/d84c4c7b-c44b-4111-8363-f41e67613889/image.png" width="50%">

## 45.4 프로미스의 에러처리

- then은 두번째 인자로 reject함수를 받기에 에러 처리를 할 수 있다.

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .then(undefined, (err) => console.error(err)); // Error: 404
```

- 하지만 then으로 에러처리를 한다면 이전 then의 에러를 잡지 못한다.
- 또한, 가독성도 좋지 않다.

> 에러 처리는 catch 메서드를 사용하자

```js
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err)); // Error: 404
```

## 45.5 프로미스 체이닝

### 콜백 헬의 예제를 Promise로 바꿔보자.

```js
class UserStroage {
  loginUser(id, password) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (
          (id === "kim" && password === "123") ||
          (id === "lee" && password === "456")
        ) {
          resolve(id);
        } else {
          reject(new Error("not found"));
        }
      }, 2000);
    });
  }

  getRoles(user) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (user === "kim") {
          resolve({ name: "kim", role: "admin" });
        } else {
          reject(new Error("no access"));
        }
      }, 1000);
    });
  }
}

const userStroage = new UserStroage();
const id = prompt("enter your id");
const password = prompt("enter your password");

// <콜백 헬 없어짐>
userStroage
  .loginUser(id, password)
  .then(userStroage.getRoles)
  .then((user) => alert(`hi ${user.name}, ${user.role}`))
  .catch(console.log);

// Promise를 사용함으로서 콜백 함수만을 이용한 비동기 처리보다 가독성이 좋아지고
// 에러 처리 또한 가능하게 개선되었다.
```

- 위 예제에서 then -> then -> catch 순으로 후속 처리 메서드를 호출했다.
- 후속 처리 메서드는 모두 promise를 반환하므로 연속적으로 호출할 수 있다.

> 이를 `프로미스 체이닝` 이라 한다.

- 하지만, Promise 또한 콜백 헬이 없을 뿐 콜백함수를 반복함에는 변함이 없다.
- 콜백함수는 가독성이 좋지 않다.
- 이를 해결하기 위해 `async/await`가 도입되었다.

## 45.6 프로미스의 정적 메서드

- Promise는 생성자 `함수`이므로 메서드를 가질 수 있다.

### 45.6.1 Promise.resolve / Promise.reject

- Promise.resolve와 Promise.reject 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.
- Promise.resolve 메서드는 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.

```jsx
// 배열을 resolve하는 프로미스를 생성
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]

// 아래와 동일하게 동작한다
const resolvedPromise = new Promise((resolve) => resolve([1, 2, 3]));
resolvedPromise.then(console.log); // [1, 2, 3]
```

### 45.6.2 Promise.all

- Promise.all 메서드는 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 순차적으로 처리
const res = [];
requestData1()
  .then((data) => {
    res.push(data);
    return requestData2();
  })
  .then((data) => {
    res.push(data);
    return requestData3();
  })
  .then((data) => {
    res.push(data);
    console.log(res); // [1, 2, 3] ⇒ 약 6초 소요
  })
  .catch(console.error);
```

- 위 세 개의 비동기 처리는 순차적으로 처리되어 약 6초가 소요된다.
- 하지만 세 개의 비동시 처리는 서로 의존하지 않고 개별적으로 수행된다.
- 때문에 순차적으로 처리할 필요가 없다.

> Promise.all 메서드로 세 개의 비동기 처리를 동시에 배열로 전달할 수 있다.

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
  .catch(console.error);
```

- Promise.all은 인수의 배열의 모든 프로미스가 `fulfilled`되면 종료한다.
- 이때 처리가 가장 늦더라도 첫 번째 프로미스가 resolve한 처리 결과부터 차례대로 배열에 저장하고
- 그 배열을 resolve 하는 프로미스를 반환하므로 처리 순서가 보장된다.
- 즉 약 3초만에 동일한 결과를 보여 줄 수 있다.

> 만약 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면  
> 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 종료한다.

```jsx
Promise.all([
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 1')), 3000))
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 2')), 2000))
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 3')), 1000))
])
  .then(console.log)
  .catch(console.error) // Error: Error 3
```

### 45.6.3 Promise.race

- Promise.race 메서드는 Promise.all 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.
- 다만 이 메서드는 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라
- 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환한다.

```js
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000))
  new Promise((resolve) => setTimeout(() => resolve(2), 2000))
  new Promise((resolve) => setTimeout(() => resolve(3), 1000))
])
  .then(console.log) // 3
  .catch(console.error)
```

### 45.6.4 Promise.allSettled

- Promise.allSettled 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다.
- 그리고 전달받은 프로미스가 모두 settled(fulfilled or rejected) 상태가 되면 처리 결과를 배열로 반환한다.

> 이 메서드가 반환한 배열에는 fulfilled 또는 rejected 상태와는 상관없이  
> Promise.allSettled 메서드가 인수로 전달받은 모든 프로미스들의 처리 결과가 모두 담겨 있다.

```js
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error!")), 1000)
  ),
]).then(console.log);
/*
[
  {status: "fulfilled", value: 1},
  {status: "rejected", reason: Error: Error! at <anonymous>:3:54}
]
*/
```

## 45.7 마이크로태스크 큐

- 아래 예제의 로그 순서를 생각해보자.

```js
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
*/
```

- 모두 비동기 동닥이므로 1 -> 2 -> 3 으로 예상되지만 2 -> 3 -> 1 이다.

> 프로미스의 후속 처리 메서드릐 콜백함수는 태스크 큐가 아닌 `마이크로태스크 큐`에 저장 되기 때문이다.  
> 이벤트 루프는 태스크 큐 보다 마이크로태크스 큐 함수를 먼저 실행한다.

## 45.8 fetch

- fetch 함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다.
- XMLHttpRequest보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.
- fetch 함수에는 HTTP 요청을 전송할 URL과 `[HTTP 요청 메서드, HTTP 요청 헤드, 페이로드 등]`을 설정한 객체를 전달한다.

```js
const myRequest = fetch(url, [, options]);
```

- fetch 함수는 HTTP 응답을 나타내는 `Response 객체`를 래핑한 Promise 객체를 반환한다.

<img src="https://velog.velcdn.com/images/sarang_daddy/post/af3cb110-89ed-47aa-b5f1-b63617508925/image.png" width="70%">

- 후속 처리 메서드 then을 통해 promise가 resolve한 `Response 객체`를 전달 받을 수 있다.

```js
fetch("https://jsonplaceholser.typicode.com/todos/1").then((response) =>
  console.log(response)
);
```

- `Response 객체`는 다양한 프로터피를 제공한다.
- `.json()`를 통해 HTTP 응답 몸체를 취득할 수 있다.

```js
fetch("https://jsonplaceholder.typicode.com/todos/1")
  // response는 HTTP 응답을 나타내는 Response 객체이다.
  // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
  .then((response) => response.json())
  // json은 역직렬화된 HTTP 응답 몸체이다.
  .then((json) => console.log(json));
// {userId: 1, id: 1, title: "delectus aut autem", completed: false}
```

### fetch 함수의 주의 사항

```js
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생해야 하지만
// ok 가 나온다.
fetch(wrongUrl)
  .then(() => console.log("ok"))
  .catch(() => console.log("error"));
```

- fetch에서는 부적절한 URL 지정되어 catch에서 error가 나와야 하겠지만 ok가 출력된다.

```
fetch 함수가 반환하는 프로미스는 기본적으로 404 Not Found나 500 Internal Server Error와 같은 HTTP 에러가 발생해도
에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve한다.
오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject한다.
```

> 때문에, fetch 함수를 사용할 때는 다음과 같이 fetch 함수가 반환한 promise가 resolve한  
> 불리언 타입의 ok 생태를 확인해 명시적으로 에러를 처리할 필요가 있다.

```js
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 404 Not Found 에러가 발생한다.
fetch(wrongUrl)
  // response는 HTTP 응답을 나타내는 Response 객체다.
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((todo) => console.log(todo))
  .catch((err) => console.error(err));
```

- 참고로 axios는 모든 HTTP 에러를 reject하는 프로미스를 반환한다.
- 따라서 모든 에러를 catch에서 처리할 수 있어서 편하다.
- 또한, 인터셉터, 요청 설정 등 다양한 기능을 지원한다.

### fetch 사용 예제 코드

```js
// fetch 함수
const request = {
  get(url) {
    return fetch(url);
  },
  post(url, payload) {
    return fetch(url, {
      method: "POST",
      headers: { "content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
  },
  patch(url, payload) {
    return fetch(url, {
      method: "PATCH",
      headers: { "content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
  },
  delete(url) {
    return fetch(url, { method: "DELETE" });
  },
};

// GET
request
  .get("https://jsonplaceholder.typicode.com/todos/1")
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((todos) => console.log(todos))
  .catch((err) => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: false}

// POST
request
  .post("https://jsonplaceholder.typicode.com/todos", {
    userId: 1,
    title: "JavaScript",
    completed: false,
  })
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((todos) => console.log(todos))
  .catch((err) => console.error(err));
// {userId: 1, title: "JavaScript", completed: false, id: 201}

// PATCH
request
  .patch("https://jsonplaceholder.typicode.com/todos/1", {
    completed: true,
  })
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((todos) => console.log(todos))
  .catch((err) => console.error(err));
// {userId: 1, id: 1, title: "delectus aut autem", completed: true}

// DELETE
request
  .delete("https://jsonplaceholder.typicode.com/todos/1")
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((todos) => console.log(todos))
  .catch((err) => console.error(err));
// {}
```
